"""Remove type, source_type, and external_id fields from Resource model

Revision ID: 6983b67acb4f
Revises: 39aaff9912c7
Create Date: 2025-03-06 00:46:01.649710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6983b67acb4f'
down_revision = '39aaff9912c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('source_type')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
